from task.train.attack.mp import ModelPoisonTrainTask
from task.train.attack.lie import LIETrainTask
from task.train.attack.gussian import GuassianTrainTask
from task.train.attack.adv_item import AdverItemTrainTask
from task.train.attack.adv_item_norm import AdverItemNormTrainTask
from task.train.attack.adv_item_elem import AdverItemElemTrainTask
from task.train.attack.adv_item_elem_norm import AdverItemElemNormTrainTask
from task.train.attack.wo_news import WoNewsTrainTask
from task.train.attack.wo_user import WoUserTrainTask
from task.train.attack.wo_quan import WoQuanTrainTask